version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - pwd
      - pip3 install boto3
      - pip3 install awscli --upgrade --user
      - aws --version
      - ls

  build:
    on-failure: CONTINUE
    commands:
      - printenv
      - cd $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR_DeployOutputsArtifact
      - cat cloudformationOutputs.json

      #################### App ####################
      - cd $CODEBUILD_SRC_DIR_DeployOutputsArtifact
      - APP_BUCKET_NAME=$(cat cloudformationOutputs.json | jq -r .AppBucket)
      - echo "APP BUCKET NAME:"
      - echo $APP_BUCKET_NAME
      - CLOUDFRONT_APP_DISTRIBUTION_ID=`cat cloudformationOutputs.json | jq -r .AppCloudfrontDistributionId`
      - cp cloudformationOutputs.json $CODEBUILD_SRC_DIR/app-game/src
      - cd $CODEBUILD_SRC_DIR/app-game
      - npm install
      - echo "running build..."
      - npm run build
      - echo "build completed"
      - ls

  post_build:
    commands:
      - printenv
      - cd $CODEBUILD_SRC_DIR

      #################### App ####################
      - echo $APP_BUCKET_NAME
      - aws s3 cp app-game/dist/ s3://$APP_BUCKET_NAME --recursive
      - echo $CLOUDFRONT_APP_DISTRIBUTION_ID
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_APP_DISTRIBUTION_ID --paths "/*"

